name: Release

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '#')"
    strategy:
      matrix:
        sm-version: ['1.12.7053']
    
    steps:
      - name: Install Checkout
        uses: actions/checkout@v1
      
      - name: Install Setup SP ${{ matrix.sm-version }}
        uses: rumblefrog/setup-sp@master
        with:
          version: ${{ matrix.sm-version }}
      
      - name: Get GitHub Env
        run: |
          echo "PLUGIN_VERSION<<EOF" >> $GITHUB_ENV
          git rev-list --count HEAD >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      
      - name: Install Misc
        run: |
          echo "SCRIPTS_PATH=addons/sourcemod/scripting" >> $GITHUB_ENV
          cd addons/sourcemod/scripting
          cd include
          wget "https://raw.githubusercontent.com/DoctorMcKay/sourcemod-plugins/master/scripting/include/morecolors.inc"
          wget "https://raw.githubusercontent.com/peace-maker/DHooks2/dynhooks/sourcemod_files/scripting/include/dhooks.inc"
          wget "https://raw.githubusercontent.com/asherkin/TF2Items/master/pawn/tf2items.inc"
          wget "https://raw.githubusercontent.com/FlaminSarge/tf2attributes/master/scripting/include/tf2attributes.inc"
          wget "https://raw.githubusercontent.com/haxtonsale/LoadSoundScript/master/sourcepawn/loadsoundscript.inc"
          wget "https://raw.githubusercontent.com/Adrianilloo/Collisionhook/master/extra/collisionhook.inc"
          wget "https://raw.githubusercontent.com/nosoop/SM-TFEconData/master/scripting/include/tf_econ_data.inc"
          wget "https://raw.githubusercontent.com/nosoop/SM-TFUtils/master/scripting/include/tf2utils.inc"
          wget "https://raw.githubusercontent.com/Batfoxkid/File-Network/main/scripting/include/filenetwork.inc"
          wget "https://raw.githubusercontent.com/nosoop/SMExt-SourceScramble/master/scripting/include/sourcescramble.inc"
          wget "https://raw.githubusercontent.com/TF2-DMB/CBaseNPC/master/scripting/include/cbasenpc.inc"
          mkdir cbasenpc
          cd cbasenpc
          wget "https://raw.githubusercontent.com/TF2-DMB/CBaseNPC/master/scripting/include/cbasenpc/activity.inc"
          wget "https://raw.githubusercontent.com/TF2-DMB/CBaseNPC/master/scripting/include/cbasenpc/baseanimating.inc"
          wget "https://raw.githubusercontent.com/TF2-DMB/CBaseNPC/master/scripting/include/cbasenpc/baseanimatingoverlay.inc"
          wget "https://raw.githubusercontent.com/TF2-DMB/CBaseNPC/master/scripting/include/cbasenpc/basecombatcharacter.inc"
          wget "https://raw.githubusercontent.com/TF2-DMB/CBaseNPC/master/scripting/include/cbasenpc/baseentity.inc"
          wget "https://raw.githubusercontent.com/TF2-DMB/CBaseNPC/master/scripting/include/cbasenpc/entityfactory.inc"
          wget "https://raw.githubusercontent.com/TF2-DMB/CBaseNPC/master/scripting/include/cbasenpc/matrix.inc"
          wget "https://raw.githubusercontent.com/TF2-DMB/CBaseNPC/master/scripting/include/cbasenpc/nav.inc"
          wget "https://raw.githubusercontent.com/TF2-DMB/CBaseNPC/master/scripting/include/cbasenpc/nextbot.inc"
          wget "https://raw.githubusercontent.com/TF2-DMB/CBaseNPC/master/scripting/include/cbasenpc/takedamageinfo.inc"
          wget "https://raw.githubusercontent.com/TF2-DMB/CBaseNPC/master/scripting/include/cbasenpc/util.inc"
          mkdir tf
          wget "https://raw.githubusercontent.com/TF2-DMB/CBaseNPC/master/scripting/include/cbasenpc/tf/nav.inc" -O "tf/nav.inc"
          mkdir nextbot
          cd nextbot
          wget "https://raw.githubusercontent.com/TF2-DMB/CBaseNPC/master/scripting/include/cbasenpc/nextbot/behavior.inc"
          wget "https://raw.githubusercontent.com/TF2-DMB/CBaseNPC/master/scripting/include/cbasenpc/nextbot/body.inc"
          wget "https://raw.githubusercontent.com/TF2-DMB/CBaseNPC/master/scripting/include/cbasenpc/nextbot/intention.inc"
          wget "https://raw.githubusercontent.com/TF2-DMB/CBaseNPC/master/scripting/include/cbasenpc/nextbot/knownentity.inc"
          wget "https://raw.githubusercontent.com/TF2-DMB/CBaseNPC/master/scripting/include/cbasenpc/nextbot/locomotion.inc"
          wget "https://raw.githubusercontent.com/TF2-DMB/CBaseNPC/master/scripting/include/cbasenpc/nextbot/path.inc"
          wget "https://raw.githubusercontent.com/TF2-DMB/CBaseNPC/master/scripting/include/cbasenpc/nextbot/vision.inc"
          mkdir path
          cd path
          wget "https://raw.githubusercontent.com/TF2-DMB/CBaseNPC/master/scripting/include/cbasenpc/nextbot/path/chase.inc"
          wget "https://raw.githubusercontent.com/TF2-DMB/CBaseNPC/master/scripting/include/cbasenpc/nextbot/path/follower.inc"
        working-directory: ./
      
      - name: Compile ${{ matrix.sm-version }}
        run: |
          mkdir -p plugins
          spcomp -E -O2 -v2 -i "include" -o "plugins/zombie_riot.smx" zombie_riot.sp
        working-directory: ${{ env.SCRIPTS_PATH }}
      
      - name: Setup Package
        run: |
          mkdir -p Update-Zombie-Riot/configs
          cp -r addons/sourcemod/scripting/plugins Update-Zombie-Riot
          cp -r addons/sourcemod/translations Update-Zombie-Riot
          cp -r addons/sourcemod/gamedata Update-Zombie-Riot
          cp -r addons/sourcemod/configs/zombie_riot Update-Zombie-Riot/configs
          mkdir -p New-Install-Zombie-Riot/addons/sourcemod/configs
          cp -r models New-Install-Zombie-Riot
          cp -r materials New-Install-Zombie-Riot
          cp -r sound New-Install-Zombie-Riot
          cp -r addons/sourcemod/scripting/plugins New-Install-Zombie-Riot/addons/sourcemod
          cp -r addons/sourcemod/translations New-Install-Zombie-Riot/addons/sourcemod
          cp -r addons/sourcemod/gamedata New-Install-Zombie-Riot/addons/sourcemod
          cp -r addons/sourcemod/configs/zombie_riot New-Install-Zombie-Riot/addons/sourcemod/configs
        working-directory: ./
      
      - name: Package Update
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r Update-Zombie-Riot-v${{env.PLUGIN_VERSION}}.zip New-Install-Zombie-Riot
      
      - name: Package Full
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r New-Install-Zombie-Riot-v${{env.PLUGIN_VERSION}}.zip New-Install-Zombie-Riot
      
      - name: Release
        uses: softprops/action-gh-release@master
        with:
          tag_name: v${{env.PLUGIN_VERSION}}
          files: |
            New-Install-Zombie-Riot-v${{env.PLUGIN_VERSION}}.zip
            Update-Zombie-Riot-v${{env.PLUGIN_VERSION}}.zip
